import { baseApi } from "../../api/baseApi"; // Assuming baseApi is correctly set up for your API base URL and configurations

const popularBrandApi = baseApi.injectEndpoints({
    endpoints: (builder) => ({
        popularBrand: builder.query({
            query: () => ({
                url: "https://node.perfectobd.com/api/node/popular-brand", // Endpoint for fetching popular brands
                method: "GET",
            }),
        }),
    }),
    overrideExisting: false, // Set to true if you want to override existing endpoints
});

// Export the hook generated by the API slice
export const { usePopularBrandQuery } = popularBrandApi;

export default popularBrandApi;
